In [1]:
import pandas as pd

In [2]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [5]:
"subhajit".replace("s", "S")

'Subhajit'

In [6]:
df['Name'].str.replace("Mr.", "Sir", regex=False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [7]:
df['Name'].head()       ## Wants to see the original, still "Mr."

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [8]:
df.loc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [9]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [10]:
df.loc[1, 'Name']       ## Another way to get the same result

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [11]:
start = df.loc[1, 'Name'].find("(")

In [12]:
start

27

In [13]:
end = df.loc[1, 'Name'].find(")")

In [14]:
end

50

In [15]:
df.loc[1, 'Name'][0:start]

'Cumings, Mrs. John Bradley '

In [16]:
df.loc[1, 'Name'][end+1:]

''

In [17]:
df.loc[1, 'Name'][0:start] + df.loc[1, 'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [18]:
def remove_substring(name):         ## This function is used to remove to particular sub-string.
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:]
    new_name = new_name.strip()
    return new_name

In [19]:
df["Name_trimmed"] = df["Name"].apply(remove_substring)

In [20]:
df["Name_trimmed"].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_trimmed, dtype: str

In [21]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [22]:
df.loc[1, 'Name_trimmed']

'Cumings, Mrs. John Bradley'

In [23]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_trimmed
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen HarriBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. LainHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William HenrAllen, Mr. William Henry"

In Python, a **RegEx (Regular Expression)**, is a powerful sequence of characters that forms a search pattern used to find, match, extract, or manipulate text. Instead of searching for exact words, regex allows you to search for complex patterns, such as verifying if a string looks like an email address, extracting phone numbers from a document, or replacing specific formatting.

Python handles regular expressions through a built-in standard library module called re, which you must import into your code.

In [24]:
# Replace Substrings with Regex : regular expression

# The partern that we target starts with "("  
# * means zero or more
# . match any character
# "\(*\)"
# "\(.*\)"  ## We are trying to replace anything that comes with "(", ")" and any charecter in between, we want to replace with "" (blank).
# df['Name'].str.replace("\\(.*\\)", "", regex=True).head()     ## In windows.    

df['Name'].str.replace(r"\(.*\)", "", regex=True).head()        ## will work in all the system mac, linux, windows.

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

| Part | Meaning                                                              |
| ---- | -------------------------------------------------------------------- |
| `r`  | Raw string literal — tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` — matches a literal opening parenthesis                  |
| `.*` | Dot `.` matches **any character**, and `*` means **zero or more**    |
| `\)` | Escaped `)` — matches a literal closing parenthesis                  |

In [25]:
# windows : \\
df['Name'].str.replace("\\(.*\\)", "", regex=True).head()   ## This code only work in windows systems.

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

With the help of Regex, now I am able to target what I want. Unless, we have to write our own logic to do that.

In [26]:
'''
hello@ghail@abc.com  -->  Is that a valid email address.

To check validation we have to write our own python logic 

OR

We can also create a regex pattern, which will tell us these above email is correct or not.
'''

'\nhello@ghail@abc.com  -->  Is that a valid email address.\n\nTo check validation we have to write our own python logic \n\nOR\n\nWe can also create a regex pattern, which will tell us these above email is correct or not.\n'

In [27]:
import re

In [28]:
def is_valid_email(email):
    # Regex Breakdown:
    # ^[a-zA-Z0-9._%+-]+ : Alphanumeric + common symbols in username
    # @                  : Mandatory @ symbol
    # [a-zA-Z0-9.-]+     : Alphanumeric, dots, or hyphens in domain
    # \.[a-zA-Z]{2,}$    : Must end with a dot followed by 2 or more letters
    
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # re.fullmatch returns a Match object if valid, otherwise None
    if re.fullmatch(pattern, email):
        return True
    return False

# Test cases
emails = ["user@example.com", "invalid-email", "name.surname@sub.domain.org", "hello@ghail@abc.com"]
for e in emails:
    print(f"{e}: {'Valid' if is_valid_email(e) else 'Invalid'}")

user@example.com: Valid
invalid-email: Invalid
name.surname@sub.domain.org: Valid
hello@ghail@abc.com: Invalid

# Split and Access Elements

In [29]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_trimmed
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen HarriBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. LainHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William HenrAllen, Mr. William Henry"

In [30]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [31]:
df['Name'].str.split(",")

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [32]:
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [33]:
df['Name'].str.split()[0]       ## By default, splits from spaces

['Braund,', 'Mr.', 'Owen', 'Harris']

In [34]:
df['Name'].str.split()

0                           [Braund,, Mr., Owen, Harris]
1      [Cumings,, Mrs., John, Bradley, (Florence, Bri...
2                             [Heikkinen,, Miss., Laina]
3      [Futrelle,, Mrs., Jacques, Heath, (Lily, May, ...
4                          [Allen,, Mr., William, Henry]
                             ...
886                            [Montvila,, Rev., Juozas]
887                    [Graham,, Miss., Margaret, Edith]
888       [Johnston,, Miss., Catherine, Helen, "Carrie"]
889                           [Behr,, Mr., Karl, Howell]
890                              [Dooley,, Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [35]:
df['Name'].str.split().str[0]           ## Here, we only want the zero index.

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [36]:
print(df['Name'].str.split()[0][0])

Braund,

# Strip Spaces

In [37]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_trimmed
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen HarriBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. LainHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William HenrAllen, Mr. William Henry"

In [ ]:
df['Name'].str.strip()              ## want to remove spaces from the left side and right side both

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
df['Name'].str.lstrip()             ## want to remove spaces from only the left side

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
df['Name'].str.rstrip()             ## want to remove spaces from only the right side

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

# Find Position of Substring

In [41]:
df['Name'].str.find("Mr")       ## -1 means "Mr" is not present.

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [42]:
# "Miss"
# Count passengers with “Miss” in name

df['Name'].str.contains("Miss")

0      False
1      False
2       True
3      False
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [43]:
df['Name'].str.contains("Miss").sum()

np.int64(182)

In [44]:
count = df['Name'].str.contains("Miss").sum()
print("Number of 'Miss':", count)

Number of 'Miss': 182

In [45]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [46]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [47]:
df['Name'].str.pad(width=20, side='left', fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

# Categorical Data in Pandas

### 📌 What is Categorical Data?

Categorical data is textual or labeled data that represents discrete categories.

In [48]:
class_data = {
                "Name" : ["A", "B", "C", "D"],
                "Groups" : ["G1", "G2", "G3", "G4"]
            }

In [49]:
class_df = pd.DataFrame(class_data)

In [50]:
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [51]:
# df['Groups'] > "G4"                   ## This is not making any sense right now.

In [52]:
# G3, G1, G2, G4                        ## order based from Higher to lower
# df['Groups'] > "G4"
# G1 > G4                               ## True, But we have to implement it.

In [53]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [54]:
class_df['Group_cat']= pd.Categorical(              ## Convertion, internally assigns numbers to each group
    class_df['Groups'],                             ## column we want to convert which is Group
    categories=['G3', 'G1', 'G2', 'G4'],            ## Custom order lower to higher (Ascending), G4 larsgest, G3 smallest
    # 'G3' : 1, 'G1' : 2, 'G2' : 3, 'G4' : 4
    ordered=True                                    ## Are they ordered?
)

In [55]:
class_df.info()                 ## A new column is added here, named as Group_cat, Dtype is "category".

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [56]:
class_df

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4

In [57]:
## It gives categories present in the dataframe.
class_df['Group_cat'].cat.categories        ## .cat, because of category type.

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [58]:
class_df['Group_cat'] > "G4"

0    False
1    False
2    False
3    False
Name: Group_cat, dtype: bool

In [59]:
class_df['Group_cat'] >= "G4"

0    False
1    False
2    False
3     True
Name: Group_cat, dtype: bool

In [60]:
df = pd.read_csv(titanic_dataset_github_url)

In [61]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [63]:
df['Embarked'].unique()         ## the port where a passenger boarded the ship, indicated by a single-letter code
## All the values present in the "Embarked".
## C (Cherbourg)
## Q (Queenstown)
## S (Southampton)

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [64]:
df['Embarked'] = df['Embarked'].fillna("N")     ## Remove "nan"

In [ ]:
df['Embarked'].unique()
## Let us assume,
## C (Cherbourg) --> 1000000         ## this much money "Cherbourg" brings in total
## Q (Queenstown) --> 5000000        ## this much money "Queenstown" brings in total
## S (Southampton) ---> 100000       ## this much money "Southampton" brings in total
## N --> Not provided ---> 000000    ## this much money "Not provided" brings in total

## Creating accending order according to the money
## N, S, C, Q

## Find all the passenger who's capital spending > 100000 (it means) > S, Q, C

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [66]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [67]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [68]:
df['Embarked_cust_cat']= pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'],        ## Custom order lower to higher (Ascending)
    ordered=True
)

In [ ]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [70]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [71]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [ ]:
df['Embarked_cust_cat'].cat.codes.head()        ## give us all categories with their respective numbers

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [74]:
# df['Sex']

# I want you to convert the values of Sex column and encode them in 0 & 1

df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [75]:
df['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: str

In [76]:
df['Sex_cat_custom_candidate_1'] = df['Sex'].astype('category').cat.codes

In [77]:
df['Sex_cat_custom_candidate_1'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex_cat_custom_candidate_1, dtype: int8

In [78]:
df['Sex_cat_custom_candidate_2'] = df['Sex'].replace(['female', 'male'], [0, 1])

In [79]:
df['Sex_cat_custom_candidate_2'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex_cat_custom_candidate_2, dtype: object

In [80]:
df['Sex_cat_custom_candidate_3'] = df['Sex'].apply(lambda sex: 1 if sex == 'male' else 0)

In [81]:
df['Sex_cat_custom_candidate_3'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex_cat_custom_candidate_3, dtype: int64

# Date Functionality in Pandas

In [82]:
df = pd.DataFrame({
    'event': ['Concert', 'Conference', 'Wedding'],
    'date': ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [ ]:
df.info()                       ## Here, "date" is in str

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [84]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [85]:

df['date_pandas'] = pd.to_datetime(df['date'])
# format: optional format (e.g. '%d/%m/%Y')

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [87]:
df.head()

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [88]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [89]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [90]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [91]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [92]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [93]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [94]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

# Creating Datetime Ranges

Other frequencies:

'D' → All Day

'M' → month end

'MS' → month start

'W' → weekly

'H', 'T', 'S' → hour, minute, second

In [95]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D')       ## "D" --> All Day

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [96]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='ME')      ## "ME" --> Month End

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [97]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='MS')      ## "MS" --> Month Start

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

# Date Arithmetic

In [98]:
## Timedelta() is used to singular number to the date
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [99]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [100]:
pd.Timestamp.today()

Timestamp('2026-10-06 13:20:53.392669')

In [101]:
df.head()

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [102]:
## Days remaining to the event
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [103]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -644 days +10:38:07.733473
1  Conference  2025-03-15  2025-03-15 2025-03-22 -571 days +10:38:07.733473
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -444 days +10:38:07.733473

# PANDAS COMPLETED

=================================================================

Write anything for the second commit.